# Generated by Django 4.0 on 2022-01-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVuelos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Operador',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
