# Generated by Django 4.0 on 2022-01-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVuelos', '0002_rename_curso_operador_delete_entregable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador',
            name='camada',
        ),
        migrations.AddField(
            model_name='operador',
            name='direccion',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='web',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
