# Generated by Django 4.0 on 2022-01-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVuelos', '0003_remove_operador_camada_operador_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=10)),
                ('fechaSalida', models.CharField(max_length=40)),
                ('horaSalida', models.IntegerField()),
                ('horaLlegada', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='operador',
            name='direccion',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operador',
            name='nombre',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operador',
            name='telefono',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operador',
            name='web',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
