# Generated by Django 4.0 on 2022-01-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVuelos', '0004_trayecto_alter_operador_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='direccion',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='web',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='fechaSalida',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='ruta',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
