# Generated by Django 4.0 on 2022-01-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVuelos', '0005_alter_operador_direccion_alter_operador_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('ruta', models.CharField(max_length=10, null=True)),
                ('fechaSalida', models.CharField(max_length=40, null=True)),
                ('horaSalida', models.IntegerField()),
                ('horaEstimada', models.IntegerField()),
            ],
        ),
    ]
