# Generated by Django 4.0 on 2022-01-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVuelos', '0006_itinerario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itinerario',
        ),
    ]
